# https://pub.dev/packages/pedantic_mono
include: package:pedantic_mono/analysis_options.yaml
analyzer:
#  enable-experiment:
#    - non-nullable
  exclude:
    - lib/*_original.dart
    - lib/generated_*.dart
