name: flutter_playground
description: A new Flutter application.
version: 1.0.0+1
environment:
  sdk: ">=2.6.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  provider: ^4.1.0-dev
  freezed_annotation:
  cupertino_icons: ^0.1.2
  extended_image:
    git:
      url: https://github.com/fluttercandies/extended_image.git
      ref: dev
  mono_kit:
  intl:
  flutter_hooks:
  state_notifier:
  flutter_state_notifier:
  tinycolor:
dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono:
  build_runner:
  freezed:
flutter:
  uses-material-design: true
  assets:
    - assets/images/
